# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\git\CloudDrop\CloudDrop\pyqt5_laptop\Client\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 350)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\git\\CloudDrop\\CloudDrop\\pyqt5_laptop\\Client\\1-6e875601.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(145, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(55, 125, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(55, 165, 61, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_userName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_userName.setGeometry(QtCore.QRect(125, 115, 200, 31))
        self.lineEdit_userName.setStyleSheet("\n"
"      background-color: #f0f0f0;\n"
"      border: 1px solid #ccc;\n"
"      border-radius: 10px;\n"
"      padding: 5px;\n"
"     ")
        self.lineEdit_userName.setObjectName("lineEdit_userName")
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(125, 155, 200, 31))
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.pushButton_login = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_login.setGeometry(QtCore.QRect(155, 245, 90, 35))
        self.pushButton_login.setObjectName("pushButton_login")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(90, 210, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setMouseTracking(False)
        self.label_4.setStyleSheet("color: #4B8BBE;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(170, 45, 61, 61))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("C:\\git\\CloudDrop\\CloudDrop\\pyqt5_laptop\\Client\\../cyber project/Logo project.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(170, 45, 61, 61))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("C:\\git\\CloudDrop\\CloudDrop\\pyqt5_laptop\\Client\\../../cyber project/Logo project.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setOpenExternalLinks(False)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login Page"))
        self.label.setStyleSheet(_translate("MainWindow", "\n"
"      color: #4B8BBE;\n"
"     "))
        self.label.setText(_translate("MainWindow", "Welcome!"))
        self.label_2.setText(_translate("MainWindow", "User Name:"))
        self.label_3.setText(_translate("MainWindow", "Password:"))
        self.lineEdit_password.setStyleSheet(_translate("MainWindow", "\n"
"      background-color: #f0f0f0;\n"
"      border: 1px solid #ccc;\n"
"      border-radius: 10px;\n"
"      padding: 5px;\n"
"     "))
        self.pushButton_login.setStyleSheet(_translate("MainWindow", "\n"
"      background-color: #008CBA;\n"
"      color: white;\n"
"      border-radius: 10px;\n"
"      padding: 5px;\n"
"     "))
        self.pushButton_login.setText(_translate("MainWindow", "Login"))
        self.label_4.setText(_translate("MainWindow", "Don\'t have an account?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
